player-token: |
  This string is replaced with the username of the currently targeted player.

x-token: |
  This string is replaced with the X-coordinate of the currently targeted
  block.

y-token: |
  This string is replaced with the Y-coordinate of the currently targeted
  block.

y-air-token: |
  This string is replaced with the Y-coordinate of the nearest air block
  above the currently targeted block.

z-token: |
  This string is replaced with the Z-coordinate of the currently targeted
  block.

options: |
  Per-group options. Groups are determined by permissions. If a player has
  the given permission, they are considered part of that group and will have
  the corresponding power tool options. The general form is:

    - name: some.permission
      limit: 5

  A limit of -1 means unlimited.

  The name "default" is special and is used if the player has none of the given
  permissions. Only the first permission matched is used.

powertools: |
  Global power tools, usable by anyone with the powertool.use permission.
  The general form is:

    item_id_or_name:
      left-click: command-to-execute-when-left-clicked
      right-click: command-to-execute-when-right-clicked
      run-as-console: true/false
      permissions:
      - perm1
      - perm2

  "left-click" or "right-click" may be omitted.
  "run-as-console" may be omitted, in which case it defaults to false.
  "permissions" may be omitted, in which case no temporary permissions will
  be granted upon use.

verbose: |
  If true, when the player selects an item on their hot bar, they will
  be reminded if the item is bound to any commands. Set to false to
  suppress this message.

omit-first-slash: |
  If true, then commands entered from the command line (i.e. for "pt left"
  and "pt right") should be entered with the first slash omitted. This only
  affects "pt left"/"pt right" and not the global power tools or player-saved
  power tools.

use-display-names: |
  If true, then items are further differentiated by their custom name, if
  given one.

debug: |
  Enable debug logging.
